/* The barrel turns around its trunnion; walls and crew stay on their foundations. */
(function(){
 const types=['barracks','archer','mage','artillery'];
 function pose(tier,scale,st){const h=PaintedWorld.layout('artillery',tier,scale).h,angle=st?.cannonAngle||0,face=st?.face||1,recoil=st?.a>=.5&&st.a<.82?Math.sin((st.a-.5)/.32*Math.PI)*4*scale:0;return{h,angle,face,x:h*.04,y:-h*.64,w:h*.72,recoil};}
 function body(g,tier,h){const f=WORLD55.towers55.frames[12+tier-1],z=h/f.h;g.save();g.beginPath();g.rect(-f.w*z/2,-h,f.w*z,h);const p=[[.37,.15],[1,.05],[1,.43],[.39,.48]];p.forEach(([x,y],i)=>i?g.lineTo((x-.5)*f.w*z,(y-1)*h):g.moveTo((x-.5)*f.w*z,(y-1)*h));g.closePath();g.clip('evenodd');PaintedWorld.blit(g,'towers',12+tier-1,0,0,h,false);g.restore();g.fillStyle='#6a563d';g.strokeStyle='#342d28';g.lineWidth=1.5;g.beginPath();g.ellipse(h*.04,-h*.62,h*.17,h*.065,0,0,Math.PI*2);g.fill();g.stroke();}
 function barrel(g,tier,scale,st,time){const p=pose(tier,scale,st),sheet=PaintedWorld.sheets.buildings58;if(!sheet?.loaded)return;const f=sheet.frames[5+tier-1],z=p.w/f.w;g.save();g.translate(p.x,p.y);g.scale(p.face,1);g.rotate(p.angle*p.face);g.translate(-p.recoil,0);g.drawImage(sheet.img,f.x,f.y,f.w,f.h,-p.w*.17,-f.h*z*.5,p.w,f.h*z);
  for(const it of Items.mods('artillery').list.filter(it=>it&&it.s<2)){const source=PaintedWorld.sheets[it.r===5?'relics58':'items57'];if(!source?.loaded)continue;const a=source.frames[18+it.s],height=it.s===1?f.h*z*.92:12*scale,width=it.s===1?height*a.w/a.h:18*scale;g.drawImage(source.img,a.x,a.y,a.w,a.h,it.s===1?p.w*.76-width/2:p.w*.33,-height/2-(it.s===0?f.h*z*.35:0),width,height);}
  if(st?.a>=.5&&st.a<.68){const a=(st.a-.5)/.18;g.fillStyle='#ffd58a';g.strokeStyle='#a66b35';g.lineWidth=1;g.beginPath();g.moveTo(p.w*.83,-6*(1-a));g.lineTo(p.w*.83+15*(1-a),-11*(1-a));g.lineTo(p.w*.83+9*(1-a),0);g.lineTo(p.w*.83+18*(1-a),6*(1-a));g.lineTo(p.w*.83,6*(1-a));g.closePath();g.fill();g.stroke();}g.restore();}
 function muzzle(T,scale=1){const p=pose(T.level,scale,T.anim),d=p.w*.83-p.recoil;return{x:T.x+p.x+Math.cos(p.angle)*d*p.face,y:T.y+2+p.y+Math.sin(p.angle)*d};}
 function door(g,tier,f,z,st){if(!(st?.door>0))return;const [cx,cy]=PaintedWorld.mounts.barracks[tier-1][1],x=(cx-.5)*f.w*z,y=(cy-1)*f.h,w=f.w*z*.15,h=f.h*z*.2,open=Math.sin(Math.min(1,st.door/.95)*Math.PI/2);g.save();g.translate(x,y);g.fillStyle='#25251d';g.strokeStyle='#6e5b3e';g.lineWidth=1;g.beginPath();g.moveTo(-w/2,h*.5);g.lineTo(-w/2,-h*.2);g.quadraticCurveTo(0,-h*.8,w/2,-h*.2);g.lineTo(w/2,h*.5);g.closePath();g.fill();g.stroke();for(const side of [-1,1]){g.save();g.translate(side*w*.5,0);g.scale(Math.max(.09,1-open),1);const x0=side<0?0:-w/2;g.fillStyle='#8b623d';g.fillRect(x0,-h*.3,w/2,h*.8);g.strokeStyle='#4b3928';g.strokeRect(x0,-h*.3,w/2,h*.8);g.fillStyle='#b19558';g.fillRect(x0,-h*.1,w/2,2);g.fillRect(x0,h*.3,w/2,2);g.restore();}g.restore();}
 window.Cannon58={pose,body,barrel,muzzle,door};
})();
