/* Quiet painted terrain and tangible, rarity-coloured tower attachments. */
(function(){
  const ground=new Image(),patterns=new WeakMap(),themes=['forest','castle','desert','ice','lava','chaos'];
  const base=new URL('../assets/sprites/',document.currentScript.src);const ready=new Promise((resolve,reject)=>{ground.onload=resolve;ground.onerror=()=>reject(new Error('Missing painted terrain'));});ground.src=new URL('quiet-ground-painted54.webp',base).href;
  PaintedWorld.ready=Promise.all([PaintedWorld.ready,ready]);
  const texture=PaintedWorld.texture;
  PaintedWorld.texture=function(g,theme,n,size){if(n!==0||!ground.complete||!ground.naturalWidth)return texture(g,theme,n,size);let cache=patterns.get(g);if(!cache){cache={};patterns.set(g,cache);}if(!cache[theme]){const i=themes.indexOf(theme),w=ground.naturalWidth/3,h=ground.naturalHeight/2,c=document.createElement('canvas');c.width=c.height=512;c.getContext('2d').drawImage(ground,(i%3)*w+2,Math.floor(i/3)*h+2,w-4,h-4,0,0,512,512);const p=g.createPattern(c,'repeat');p.setTransform(new DOMMatrix().scale((size||640)/512));cache[theme]=p;}return cache[theme];};
  MapArt.decor=function(F,paths,spots,W,H,theme,seed){const rng=ArtKit.seeded(seed),out=[],near=(x,y,r)=>spots.some(s=>Math.hypot(s.x-x,s.y-y)<r),mix={forest:['tree','tree','bush','rock'],castle:['tree','pine','rock','bush'],desert:['palm','cactus','rock','drybush'],ice:['snowpine','pine','rock','icecrystal'],lava:['deadtree','rock','rock','bones'],chaos:['deadtree','rock','voidcrystal','rock']}[theme];
    for(let y=50;y<H+40;y+=115)for(let x=45;x<W+40;x+=115){const px=x+(rng()-.5)*45,py=y+(rng()-.5)*35,dp=Math.min(...paths.map(p=>p.nearest(px,py).perp)),edge=Math.min(px,W-px,py,H-py);if(dp<110||near(px,py,95)||MapArt.wetAt(F,px,py,30)||rng()>(edge<100?.7:.2))continue;let k=mix[Math.floor(rng()*mix.length)];if(dp<160&&['tree','pine','snowpine','palm'].includes(k))k='rock';out.push({k,x:px,y:py,s:.7+rng()*.25,v:rng(),flip:rng()<.5?-1:1});}
    for(const p of F.props)out.push({...p,prop:true,s:1,v:.5,flip:1});return out.sort((a,b)=>a.y-b.y);
  };
  // Shared positions keep crew, projectiles and equipment on the same architectural surfaces.
  PaintedWorld.layout=function(type,tier,scale=1){const h=(94+tier*14)*scale*.7,crew={archer:['elf',h*.06,-h*.52],mage:['mage',h*.1,-h*.43],artillery:['dwarf',-h*.19,-h*.24]}[type];return{h,crew,base:4.9*scale};};
  function gem(g,x,y,size,col){g.save();g.translate(x,y);g.lineWidth=1.3;g.strokeStyle='#393631';const grad=g.createLinearGradient(-size,-size,size,size);grad.addColorStop(0,'#f4fff8');grad.addColorStop(.32,col);grad.addColorStop(1,ArtKit.shade(col,-.5));g.fillStyle=grad;g.beginPath();g.moveTo(0,-size);g.lineTo(size*.6,-size*.3);g.lineTo(size*.46,size*.65);g.lineTo(0,size);g.lineTo(-size*.46,size*.65);g.lineTo(-size*.6,-size*.3);g.closePath();g.fill();g.stroke();g.strokeStyle='#ffffff99';g.beginPath();g.moveTo(0,-size*.8);g.lineTo(-size*.18,-size*.2);g.lineTo(0,size*.6);g.stroke();g.restore();}
  function flag(g,x,y,size,col,time){g.save();g.translate(x,y);g.lineWidth=2;g.strokeStyle='#544334';g.beginPath();g.moveTo(0,7);g.lineTo(0,-size*1.6);g.stroke();const w=size*1.45,h=size*.85;for(let i=0;i<12;i++){const t=i/11,a=Math.sin(time*3-t*3.4)*size*.12*t;g.fillStyle=i<6?col:ArtKit.shade(col,-.1);g.fillRect(t*w,-size*1.5+a,w/11+1,h);}g.strokeStyle='#e7d5a3';g.lineWidth=1;g.beginPath();g.moveTo(2,-size*1.48);for(let i=1;i<12;i++){const t=i/11;g.lineTo(t*w,-size*1.5+Math.sin(time*3-t*3.4)*size*.12*t);}g.stroke();g.restore();}
  const iconUrl=Items.iconUrl,icons=new Map();
  Items.iconUrl=function(it){const name=Items.def(it).icon,col=Items.rar(it).col;if(!['flag','gem','crystal','frost','rune'].includes(name))return iconUrl.call(this,it);const key=name+col;if(icons.has(key))return icons.get(key);const c=document.createElement('canvas');c.width=c.height=96;const g=c.getContext('2d');name==='flag'?flag(g,17,77,36,col,0):gem(g,48,48,36,col);const u=c.toDataURL();icons.set(key,u);return u;};
  const drops=new Map(),oldBadge=Items.drawBadge;
  Items.drawBadge=function(g,it,x,y,r,time){const key=it.t+':'+it.s+':'+it.r,url=this.iconUrl(it);if(!url)return oldBadge.call(this,g,it,x,y,r,time);if(!drops.has(key)){const img=new Image();img.src=url;drops.set(key,img);}const img=drops.get(key);if(!img.complete)return;g.save();if(it.r>=4)ArtKit.glow(g,x,y,r*1.8,Items.rar(it).col,.2);g.drawImage(img,x-r*1.2,y-r*1.2,r*2.4,r*2.4);g.restore();};
  function attachments(g,type,h,scale,time){const list=Items.mods(type).list,points=[[0,-h*.92],[h*.02,-h*.66],[0,-h*.38],[-h*.26,-h*.38],[h*.26,-h*.38],[h*.12,-h*.1]];list.forEach((it,i)=>{if(!it)return;const [x,y]=points[i],col=Items.rar(it).col,name=Items.def(it).icon;
    if(name==='flag'){flag(g,-h*.19,-h*.82,14*scale,col,time);return;}
    if(['gem','crystal','frost','rune'].includes(name)){g.fillStyle='#554936';g.beginPath();g.ellipse(x,y+8*scale,9*scale,3*scale,0,0,Math.PI*2);g.fill();gem(g,x,y,10*scale,col);return;}
    // Objects sit on brackets or are bolted to the wall, rather than floating circular badges.
    g.strokeStyle='#574b3e';g.lineWidth=2*scale;g.beginPath();g.moveTo(x-9*scale,y+8*scale);g.lineTo(x+9*scale,y+8*scale);g.moveTo(x-6*scale,y+8*scale);g.lineTo(x-4*scale,y+12*scale);g.stroke();g.fillStyle=col;g.globalAlpha=.7;g.fillRect(x-7*scale,y+10*scale,14*scale,2*scale);g.globalAlpha=1;
    const n=PaintedWorld.names.indexOf(name);if(n>=0)PaintedWorld.blit(g,'equipment',n,x,y+8*scale,19*scale,false);
  });}
  Painter.tower=function(g,type,tier,x,y,scale,time,st){const types=['barracks','archer','mage','artillery'],row=types.indexOf(type);if(row<0)return;const L=PaintedWorld.layout(type,tier,scale),h=L.h;g.save();g.translate(x,y+L.base);ArtKit.shadow(g,2*scale,2*scale,27*scale,7*scale,.24);PaintedWorld.blit(g,'towers',row*4+tier-1,0,0,h,false);
    if(L.crew){const [id,cx,cy]=L.crew;g.fillStyle=type==='archer'?'#987244':'#a29680';g.strokeStyle='#4b4132';g.lineWidth=1.4*scale;g.beginPath();g.ellipse(cx,cy+1*scale,12*scale,4*scale,0,0,Math.PI*2);g.fill();g.stroke();g.save();g.translate(cx,cy);if(st?.face<0)g.scale(-1,1);ArtStylized.draw(g,id,{w:-1,a:st?.a>=0?st.a:-1,t:time},19*scale);g.restore();g.strokeStyle='#716047';g.lineWidth=2*scale;g.beginPath();g.moveTo(cx-11*scale,cy);g.lineTo(cx-11*scale,cy+6*scale);g.lineTo(cx+11*scale,cy+6*scale);g.lineTo(cx+11*scale,cy);g.stroke();}
    attachments(g,type,h,scale,time);g.restore();
  };
  // The ground foundation never falls with the building. Its soil matches the current biome.
  PaintedWorld.foundation=function(g,x,y,type,tier,fall){const T=MapArt.TH[Game.map?.def.theme||'forest'];g.save();g.translate(x,y+5);g.fillStyle=ArtKit.shade(T.g0,-.15);g.strokeStyle=ArtKit.shade(T.g0,-.3);g.lineWidth=2;g.beginPath();g.ellipse(0,0,39,13,0,0,Math.PI*2);g.fill();g.stroke();g.fillStyle=T.roadD;g.globalAlpha=.55;g.beginPath();g.ellipse(0,1,30,8,0,0,Math.PI*2);g.fill();g.restore();};
})();
