/* Mobile input, bounded rendering cost, and tactical enemy support. */
(function(){
 if(!CanvasRenderingContext2D.prototype.roundRect)CanvasRenderingContext2D.prototype.roundRect=function(x,y,w,h,r){r=Math.min(Number(r)||4,w/2,h/2);this.moveTo(x+r,y);this.arcTo(x+w,y,x+w,y+h,r);this.arcTo(x+w,y+h,x,y+h,r);this.arcTo(x,y+h,x,y,r);this.arcTo(x,y,x+w,y,r);this.closePath();return this;};
 const coarse=matchMedia('(pointer: coarse)').matches,low=(navigator.deviceMemory||4)<=4;
 const showScreen=UI.showScreen;UI.showScreen=function(id){document.body.classList.toggle('battle55',id==='screen-game');return showScreen.call(this,id);};
 Game.measure=function(){const r=this.wrap.getBoundingClientRect();this.viewW=Math.max(1,r.width);this.viewH=Math.max(1,r.height);this.q=this.q||Save.data.settings.q||1;this.dpr=Math.max(.7,Math.min(coarse||low?1.5:2,devicePixelRatio||1)*this.q);this.canvas.width=Math.round(this.viewW*this.dpr);this.canvas.height=Math.round(this.viewH*this.dpr);this.canvas.style.width=this.viewW+'px';this.canvas.style.height=this.viewH+'px';Painter.ppuCap=2;};
 Game.renderBg=function(){this.bg=Level.renderBackground(this.map,Math.min(1.3,Math.max(.65,Camera.minZoom*this.dpr*1.1)));};Game.drawAtmosphere=function(){};
 const particle=Effects.particle;Effects.particle=function(...a){if(this.particles.length<(low?100:180))return particle.apply(this,a);};const burst=Effects.burst;Effects.burst=function(x,y,c,n,...a){return burst.call(this,x,y,c,Math.min(n,low?8:14),...a);};
 const comic=Effects.comic;let comicClock=0;Effects.comic=function(...a){const now=performance.now();if(now-comicClock<420&&!a[4])return;comicClock=now;return comic.apply(this,a);};
 const updateEnemies=Enemies.update;Enemies.update=function(dt){updateEnemies.call(this,dt);for(const e of this.list){if(!e.alive||!e.def.healer)continue;e.healClock=(e.healClock||0)-dt;if(e.healClock>0)continue;e.healClock=4;for(const o of this.list)if(o.alive&&o!==e&&Math.hypot(o.x-e.x,o.y-e.y)<100)o.hp=Math.min(o.maxHp,o.hp+o.maxHp*.055);Effects.ring(e.x,e.y,10,100,.65,'#b5d88c',3);}};
 const hit=Combat.hitEnemy;Combat.hitEnemy=function(e,dmg,type,pen){if(e.type==='shellGuard'&&type==='physical'&&e.state==='walk')dmg=Array.isArray(dmg)?dmg.map(v=>v*.8):dmg*.8;return hit.call(this,e,dmg,type,pen);};
 const originalStart=Game.start;Game.start=function(i){originalStart.call(this,i);mountStick();};
 function mountStick(){let stick=document.getElementById('hero-joystick');if(stick)return;stick=document.createElement('div');stick.id='hero-joystick';stick.setAttribute('role','application');stick.setAttribute('aria-label','Kéo để điều khiển tướng');stick.innerHTML='<i></i><span>DI CHUYỂN TƯỚNG</span>';Game.wrap.append(stick);let pointer=null,origin=null;const knob=stick.querySelector('i');
  function aim(e){const r=stick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,len=Math.hypot(dx,dy),cap=r.width*.32,k=len>cap?cap/len:1;Game.heroStick={x:len<7?0:dx/Math.max(cap,len),y:len<7?0:dy/Math.max(cap,len)};knob.style.transform=`translate(${dx*k}px,${dy*k}px)`;}
  stick.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();if(Game.paused||!Units.hero?.active)return;pointer=e.pointerId;stick.setPointerCapture(pointer);Game.heroSelected=true;Game.sel=null;UI.closeRing();stick.classList.add('using');aim(e);});stick.addEventListener('pointermove',e=>{if(e.pointerId===pointer){e.preventDefault();aim(e);}});const end=e=>{if(pointer!==e.pointerId)return;pointer=null;Game.heroStick=null;knob.style.transform='';stick.classList.remove('using');const h=Units.hero;if(h?.active){h.postX=h.x;h.postY=h.y;h.state='post';h.moving=false;}Game.heroSelected=false;};stick.addEventListener('pointerup',end);stick.addEventListener('pointercancel',end);stick.addEventListener('lostpointercapture',end);
 }
 const update=Game.update;Game.update=function(dt){const v=this.heroStick,h=Units.hero;if(v&&h?.active&&!this.paused){h.postX=Math.max(20,Math.min(this.map.W-25,h.x+v.x*65));h.postY=Math.max(30,Math.min(this.map.H-20,h.y+v.y*65));h.state='move';h.target=null;h.atk=-1;}update.call(this,dt);};
 const tap=Game.onTap;Game.onTap=function(x,y){if(this.paused)return;const h=Units.hero;if(h?.active&&this.heroSelected&&!Spells.armed&&!this.rallyFor){Hero.moveHero(h,Math.max(20,Math.min(this.map.W-25,x)),Math.max(30,Math.min(this.map.H-20,y)));this.heroSelected=true;return;}return tap.call(this,x,y);};
 const pause=Game.pause;Game.pause=function(){this.heroStick=null;return pause.call(this);};
 // Restrict frozen title/codex artwork to one render per visit. Battle retains the frame loop.
 const settings=UI.renderSettings;UI.renderSettings=function(){settings.call(this);document.querySelectorAll('[data-action="art3d"]').forEach(e=>e.remove());};
})();
