/* Two distinct champions per faction, and a connected winding campaign. */
(function(){
 const add=(id,base,v)=>CONFIG.heroes[id]={...CONFIG.heroes[base],...v,skill:{...v.skill},skill2:{...v.skill2},story:v.story};
 add('veyra','aldric',{name:'Veyra Búa Thề',race:'Người',role:'Paladin · Phá giáp',color:'#e7bd73',hp:440,armor:.35,damage:[25,34],range:0,proj:null,speed:91,unlockLevel:15,talentNames:['Búa thề','Khiên vàng','Tiên phong'],talentStats:['dmg','arm','hp'],skill:{name:'Búa Phán Quyết',damage:145,radius:110,cooldown:26,short:'Gọi ba nhát búa giáng xuống điểm chọn, phá đội hình và làm choáng quái thường.'},skill2:{name:'Đội Cận Vệ',cooldown:29,level:10,short:'Hai cận vệ xuất hiện ở điểm chọn, chắn quái và chiến đấu trong 14 giây.'},story:'Veyra rèn búa từ khóa cổng đã gãy trong cuộc vây thành. Cô cùng đội cận vệ giữ lối rút cho dân, rồi mang lời thề ấy theo đoàn quân đi tìm năm Ấn Cổng.'});
 add('thalen','lyra',{name:'Thalen Lá Đêm',race:'Elf',role:'Song đao · Đột kích',color:'#8bc28b',hp:310,armor:.22,damage:[26,36],range:0,proj:null,air:false,speed:116,unlockLevel:18,talentNames:['Song đao','Bóng lá','Rễ cổ'],talentStats:['dmg','spd','skill'],skill:{name:'Đột Kích Lá',damage:155,radius:85,cooldown:21,short:'Lướt tới điểm chọn rồi chém song đao. Cần chọn đúng vị trí để đón nhóm quái.'},skill2:{name:'Bẫy Rễ',cooldown:24,level:10,short:'Đặt vùng rễ trong 5 giây, trói quái thường và làm chậm boss đi qua.'},story:'Thalen theo dấu những kẻ đốn Cây Tổ qua khe suối. Hai lưỡi đao bằng lá thép giữ đường cho người Elf rút về thành; giờ anh dùng chúng để cắt đường tiến của quân Hư Vô.'});
 add('oria','selene',{name:'Oria Đèn Trăng',race:'Phù thủy',role:'Tinh cầu · Ảo ảnh',color:'#90bcdf',hp:275,armor:.14,damage:[24,34],range:155,proj:'bolt',air:true,speed:94,unlockLevel:21,talentNames:['Tinh cầu','Ảo ảnh','Áo trăng'],talentStats:['dmg','skill','hp'],skill:{name:'Sao Rơi Tím',damage:140,radius:100,cooldown:27,short:'Ba tinh cầu rơi lần lượt xuống điểm chọn, gây sát thương phép lan.'},skill2:{name:'Ảnh Ảo Đèn Trăng',cooldown:30,level:10,short:'Tạo một ảo ảnh ở điểm chọn, bắn phép trong 12 giây và thu hút quái.'},story:'Oria tìm được ngọn đèn không tắt trong thư viện Tháp Sao. Mỗi mảnh kính lưu một bầu trời đã mất. Cô soi đường qua các đảo trôi bằng ánh trăng và những bản sao của chính mình.'});
 add('haldren','borin',{name:'Haldren Búa Núi',race:'Người lùn',role:'Búa nặng · Giáp rèn',color:'#d1b58a',hp:560,armor:.42,damage:[30,43],range:0,proj:null,air:false,speed:81,unlockLevel:24,talentNames:['Địa chấn','Giáp rèn','Tim núi'],talentStats:['dmg','arm','hp'],skill:{name:'Búa Địa Chấn',damage:175,radius:125,cooldown:26,short:'Đập búa xuống điểm chọn, gây sóng chấn động và choáng quái trên mặt đất.'},skill2:{name:'Giáp Rèn Sơn Thành',cooldown:28,level:10,short:'Phủ giáp rèn cho tướng và lính quanh điểm chọn, giảm sát thương trong 6 giây.'},story:'Haldren từng giữ nhịp búa cho cây cầu duy nhất qua khe băng. Khi lò rèn sập, ông mang chiếc búa cuối cùng ra khỏi núi, thề dựng lại từng cây cầu đoàn quân cần đi qua.'});
 add('brakka','nara',{name:'Brakka Song Rìu',race:'Orc',role:'Cuồng phong · Kéo địch',color:'#dc9278',hp:510,armor:.24,damage:[31,44],range:0,proj:null,air:false,speed:106,unlockLevel:27,talentNames:['Song rìu','Chiến bước','Sức bền'],talentStats:['dmg','spd','hp'],skill:{name:'Lốc Rìu',damage:65,radius:100,cooldown:25,short:'Lướt tới điểm chọn rồi xoay rìu ba nhịp, đánh các quái ở gần.'},skill2:{name:'Móc Chiến Trận',cooldown:22,level:10,short:'Quăng móc vào quái tại điểm chọn, kéo lùi nó trên đường và làm choáng ngắn.'},story:'Brakka cắt cờ của bộ tộc xâm lược để cứu người bị bắt. Cô cùng Gorak lập lời thề mới: sức mạnh Orc dùng để giữ cổng, không đốt những ngôi nhà bên ngoài cổng.'});
 CONFIG.heroes.aldric.skill={name:'Đội Cận Vệ Cổng',damage:125,radius:100,cooldown:30,short:'Gọi hai cận vệ tại điểm chọn. Họ chắn đường và chiến đấu trong 16 giây.'};
 CONFIG.heroes.aldric.skill2={name:'Khiên Phản Kích',cooldown:21,level:10,short:'Caelan lao tới điểm chọn, nâng khiên và đánh bật quái áp sát.'};
 CONFIG.pathWidth=56;
 CONFIG.towers.barracks.engage=140;
 for(let r=0;r<5;r++){
  const amp=[145,170,130,155,165][r],phase=[0,.65,-.6,1.3,-1.1][r],y=x=>320+amp*Math.sin(x*Math.PI*2/1280+phase)+35*Math.sin(x*Math.PI/3840+r*.7);
  const route=Array.from({length:97},(_,k)=>[k*80,y(k*80)]);
  for(let s=0;s<6;s++){const L=CONFIG.levels[r*6+s],start=s*1280;L.ipaths=[Array.from({length:19},(_,k)=>[(k-1)*80,y(start+(k-1)*80)])];L.route={...L.route,points:route,entry:[0,y(start)],exit:[1280,y(start+1280)]};L.name=CONFIG.regions[r].name;L.spots=r<3?6:5;for(const p of L.feat.props||[])if(['castle','portal','fort'].includes(p.k))p.y=y(start+p.x)+10;}
 }
 window.REALM57={newHeroes:['veyra','thalen','oria','haldren','brakka']};
})();
