/* Scene composition is stage-specific; towers use compact nearby footprints. */
(function(){
 let current=null;const render=MapArt.render,texture=PaintedWorld.texture,patterns=new Map();
 MapArt.render=function(map,res){current=map;try{return render.call(this,map,res);}finally{current=null;}};
 PaintedWorld.texture=function(g,theme,n,size){if(n!==0||!current)return texture.call(this,g,theme,n,size);const key=current.index;if(!patterns.has(key)){const c=document.createElement('canvas');c.width=1280;c.height=640;const p=c.getContext('2d'),C=PaintedWorld.colors[theme],sc=current.def.scene59,rnd=ArtKit.seeded(sc.seed);p.fillStyle=C[0];p.fillRect(0,0,1280,640);
  for(let k=0;k<28;k++){const x=rnd()*1280,y=rnd()*640,rx=45+rnd()*135,ry=20+rnd()*55,gr=p.createRadialGradient(x,y,5,x,y,rx);gr.addColorStop(0,ArtKit.alpha(C[k%2+1],.28));gr.addColorStop(1,ArtKit.alpha(C[k%2+1],0));p.fillStyle=gr;p.save();p.translate(x,y);p.scale(1,ry/rx);p.beginPath();p.arc(0,0,rx,0,7);p.fill();p.restore();}
  if(sc.kind===2||sc.kind===4){for(let j=0;j<5;j++){const y=j%2?590:45,x=100+j*235+(sc.seed%71);p.fillStyle=ArtKit.alpha(C[2],.25);p.strokeStyle=ArtKit.alpha(C[1],.45);p.lineWidth=2;p.beginPath();p.moveTo(x-75,y);p.bezierCurveTo(x-20,y-25,x+40,y+20,x+90,y-10);p.lineTo(x+110,y+22);p.bezierCurveTo(x+40,y+45,x-35,y+12,x-75,y);p.fill();p.stroke();}}
  for(let k=0;k<170;k++){p.fillStyle=ArtKit.alpha(C[k%3],.12);p.beginPath();p.ellipse(rnd()*1280,rnd()*640,3+rnd()*17,1+rnd()*4,rnd(),0,7);p.fill();}patterns.set(key,c);if(patterns.size>6)patterns.delete(patterns.keys().next().value);}return g.createPattern(patterns.get(key),'no-repeat');};
 MapArt.decor=function(F,paths,spots,W,H,theme,seed){const sc=CONFIG.levels[Math.round((seed-7)/31)]?.scene59||{kind:0,seed},rnd=ArtKit.seeded(sc.seed),out=[],kind=sc.kind;
  const mixes={forest:['tree','pine','bush','stump','rock'],castle:['tree','bush','rock','house','barrel'],ice:['snowpine','rock','icecrystal','ruin'],lava:['deadtree','rock','brazier','redcrystal','bones'],chaos:['voidcrystal','rune','rock','deadtree'],desert:['palm','rock','cactus','drybush']},mix=mixes[theme];
  const centers=Array.from({length:kind===4?4:kind===0?7:5},(_,i)=>({x:90+rnd()*(W-180),y:kind===4?150+rnd()*330:i%2?H-65-rnd()*55:100+rnd()*60}));
  for(let k=0;k<(kind===3?100:kind===4?210:kind===0?100:150);k++){const c=centers[k%centers.length],x=Math.max(60,Math.min(W-60,c.x+(rnd()-.5)*190)),y=Math.max(105,Math.min(H-22,c.y+(rnd()-.5)*135));if(paths.some(p=>p.nearest(x,y).perp<69)||spots.some(s=>Math.hypot(x-s.x,y-s.y)<49)||MapArt.wetAt(F,x,y,18)||out.some(o=>Math.hypot(x-o.x,y-o.y)<33))continue;let prop=mix[Math.floor(rnd()*mix.length)];if(kind===2&&rnd()<.65)prop='rock';if(kind===3&&theme==='castle'&&k%5===0)prop='house';out.push({k:prop,x,y,s:.62+rnd()*.3,v:rnd(),flip:rnd()<.5?-1:1});}
  for(const path of paths)for(let d=130;d<path.length-110;d+=175){const q=path.pointAt(d,{}),side=Math.floor(d/175)%2?1:-1,x=q.x+q.nx*65*side,y=q.y+q.ny*65*side;if(x<35||x>W-35||y<75||y>H-15||spots.some(s=>Math.hypot(s.x-x,s.y-y)<43)||MapArt.wetAt(F,x,y,12)||paths.some(p=>p.nearest(x,y).perp<53))continue;out.push({k:theme==='forest'?'bush':theme==='chaos'?'voidcrystal':'rock',x,y,s:.45,v:rnd(),flip:1});}for(const p of F.props)out.push({...p,prop:true,v:.5,flip:1});return out.sort((a,b)=>a.y-b.y);
 };
 const build=Level.build;Level.build=function(index){const m=build.call(this,index),candidates=[],hw=38,hh=72,pad=CONFIG.pathWidth/2+4;
  for(let y=100;y<m.H-28;y+=16)for(let x=105;x<m.W-125;x+=18){const near=Math.min(...m.paths.map(p=>p.nearest(x,y).perp));if(near<37||near>113||MapArt.wetAt(m.feat,x,y,38)||m.feat.props.some(p=>Math.hypot(p.x-x,p.y-y)<85))continue;if(m.paths.some(p=>p.points.some(q=>q.x>x-hw-pad&&q.x<x+hw+pad&&q.y>y-hh-pad&&q.y<y+5+pad)))continue;candidates.push({x,y,near});}
  const spots=[];while(candidates.length&&spots.length<m.def.spots){let best=-1,score=-Infinity;for(let i=0;i<candidates.length;i++){const p=candidates[i];if(spots.some(s=>Math.hypot(s.x-p.x,s.y-p.y)<140))continue;let cover=0;for(const path of m.paths)for(let d=100;d<path.length-50;d+=90){const q=path.pointAt(d,{});if(Math.hypot(q.x-p.x,q.y-p.y)<155&&!spots.some(s=>Math.hypot(q.x-s.x,q.y-s.y)<140))cover++;}const v=cover*20-p.near*.6;if(v>score){score=v;best=i;}}if(best<0)break;spots.push({...candidates.splice(best,1)[0],id:spots.length});}m.spots=spots;m.decor=MapArt.decor(m.feat,m.paths,spots,m.W,m.H,m.def.theme,index*31+7);return m;};
 const prop=PaintedWorld.prop;PaintedWorld.prop=function(g,d,theme){if(!d.gate59)return prop.call(this,g,d,theme);const sh=this.sheets.buildings58;if(!sh?.loaded)return false;const f=sh.frames[d.race],h=138,z=h/f.h,door=[[.50,.9],[.50,.9],[.51,.91],[.49,.91],[.50,.91]][d.race];g.drawImage(sh.img,f.x,f.y,f.w,f.h,d.x-door[0]*f.w*z,d.y-door[1]*h,f.w*z,h);return true;};
 PaintedWorld.foundation=function(){};
 window.Scenes59={footprint:{halfWidth:38,height:72},patterns};
})();
