/* Readable effects: preparation, action and fading aftermath match each command. */
(function(){
 const ids=['aldric','lyra','selene','borin','nara','veyra','thalen','oria','haldren','brakka'],cache=new Map();
 function painted(g,id,slot,x,y,r,t,life,z){if(z.physical&&id==='oria')id='borin';if(id==='borin'&&slot)return false;const sheet=PaintedWorld.sheets.fx59;if(!sheet?.loaded)return false;const i=ids.indexOf(id);if(i<0)return false;const frame=(i<5?slot:2+slot)*5+i%5,f=sheet.frames[frame];let c=cache.get(frame);if(!c){c=document.createElement('canvas');c.width=f.w;c.height=f.h;const p=c.getContext('2d');if(f.clipRects){p.beginPath();for(const b of f.clipRects)p.rect(...b);p.clip();}p.drawImage(sheet.img,f.x,f.y,f.w,f.h,0,0,f.w,f.h);cache.set(frame,c);}
 const impact=z.impact??.55,fall=(id==='oria'&&!slot||id==='veyra'&&!slot||id==='borin'&&!slot),q=Math.min(1,t/impact),persistent=slot&&['selene','thalen','borin','oria'].includes(id),alpha=Math.max(0,Math.min(1,t*9,(life-t)*5)),h=Math.min(110,Math.max(55,r*.95))*(.85+.15*Math.min(1,t*4)),w=h*f.w/f.h;
 g.save();g.translate(x,y-(fall&&t<impact?65*(1-q):0));g.globalAlpha=alpha*(persistent?.8:.92);g.scale(1+.025*Math.sin(t*9),1+.035*Math.sin(t*6));if(((id==='lyra'||id==='selene')&&!slot||id==='brakka'&&slot)&&Units.hero?.heroId===id&&Units.hero.face<0)g.scale(-1,1);if((id==='nara'||id==='brakka')&&!slot)g.rotate(Math.sin(t*7)*.15);g.drawImage(c,-w/2,-h*.85,w,h);g.restore();return true;
 }

 function draw(g,id,slot,x,y,r,t,life=1.5,z={}){if(painted(g,id,slot,x,y,r,t,life,z))return true;const fade=Math.max(0,Math.min(1,t*10,(life-t)*5)),p=Math.min(1,t/.45),color={aldric:'#85bddb',veyra:'#e1bb74',lyra:'#a3cd74',thalen:'#87be9a',selene:'#be95e1',oria:'#bd9ded',borin:'#e9b06e',haldren:'#d3b187',nara:'#e19c78',brakka:'#db8d78'}[id]||'#ead4a3';g.save();g.translate(x,y);g.globalAlpha=fade;g.lineCap='round';g.lineJoin='round';
  const ellipse=(R,col,w=2)=>{g.strokeStyle=col;g.lineWidth=w;g.beginPath();g.ellipse(0,0,R,R*.32,0,0,7);g.stroke();};
  const spark=(sx,sy,k=3)=>{g.strokeStyle='#fff2c9';g.lineWidth=1.5;g.beginPath();g.moveTo(sx-k,sy);g.lineTo(sx+k,sy);g.moveTo(sx,sy-k);g.lineTo(sx,sy+k);g.stroke();};
  const slash=(R,a=0)=>{g.save();g.rotate(a);g.fillStyle=color;g.beginPath();g.moveTo(-R*.8,0);g.bezierCurveTo(-R*.2,-R*.72,R*.85,-R*.35,R,0);g.bezierCurveTo(R*.5,-R*.2,-R*.2,-R*.42,-R*.8,0);g.fill();g.strokeStyle='#fff3d4';g.lineWidth=1.5;g.beginPath();g.moveTo(-R*.6,-R*.07);g.quadraticCurveTo(R*.23,-R*.56,R*.87,-R*.02);g.stroke();g.restore();};
  const glow=(xx,yy,rad)=>{const gr=g.createRadialGradient(xx,yy,0,xx,yy,rad);gr.addColorStop(0,color+'99');gr.addColorStop(.4,color+'44');gr.addColorStop(1,color+'00');g.fillStyle=gr;g.beginPath();g.arc(xx,yy,rad,0,7);g.fill();};
  if((id==='aldric'&&!slot)||(id==='veyra'&&slot)){const q=Math.min(1,t/.35);ellipse(r*q,color,2*(1-q)+1);for(const side of [-1,1]){const xx=side*18;glow(xx,-7,18*(1-q)+4);for(let i=0;i<4;i++){const a=i*1.6+t*2;spark(xx+Math.cos(a)*12*q,-5-Math.sin(a)*8*q-15*q,2);}}}
  else if(id==='aldric'||id==='haldren'&&slot){glow(0,-20,38);g.fillStyle=color+'55';g.strokeStyle='#f3d39b';g.lineWidth=2.5;g.beginPath();g.moveTo(-22,-43);g.quadraticCurveTo(0,-51,22,-43);g.lineTo(17,-15);g.quadraticCurveTo(12,-5,0,0);g.quadraticCurveTo(-12,-5,-17,-15);g.closePath();g.fill();g.stroke();g.strokeStyle='#fff1c8';g.lineWidth=1;g.beginPath();g.moveTo(-15,-39);g.lineTo(-12,-17);g.lineTo(0,-6);g.stroke();if(id==='aldric'&&t<.55)slash(r*p*.65,-.15);}
  else if(id==='lyra'){for(let i=0;i<(slot?3:5);i++){const a=(i-2)*.3,dist=r*p,sx=Math.cos(a)*dist,sy=Math.sin(a)*dist*.5-12;g.strokeStyle=color+'aa';g.lineWidth=3;g.beginPath();g.moveTo(sx-30*(1-p),sy+12);g.quadraticCurveTo(sx-18,sy,sx,sy);g.stroke();g.fillStyle='#f1d590';g.beginPath();g.moveTo(sx+5,sy);g.lineTo(sx-4,sy-3);g.lineTo(sx-4,sy+3);g.fill();spark(sx,sy,2);}}
  else if(id==='selene'&&!slot){const tx=(z.tx??x+r*.6)-x,ty=(z.ty??y)-y;glow(tx,ty,24);for(let layer=0;layer<2;layer++){g.strokeStyle=layer?'#f7edff':color;g.lineWidth=layer?1.4:5;g.beginPath();g.moveTo(0,-20);for(let i=1;i<=7;i++){const k=i/7;g.lineTo(tx*k+(i<7?Math.sin(i*4+t*18)*9:0),-20+(ty+20)*k+(i<7?Math.cos(i*3+t*18)*8:0));}g.stroke();}spark(tx,ty,7);}
  else if(id==='selene'){ellipse(r*.82,color);for(let i=0;i<5;i++){const a=i*1.26,xx=Math.cos(a)*r*.8,yy=Math.sin(a)*r*.26;g.strokeStyle=color;g.lineWidth=3;g.beginPath();g.moveTo(xx,yy);g.lineTo(xx,yy-28*p);g.stroke();spark(xx,yy-28*p,5);}ellipse(r*.82,'#efd9f5',1);}
  else if((id==='oria'||id==='veyra'||id==='borin')&&!slot){const impact=z.impact??.6,q=Math.min(1,t/impact),yy=-115*(1-q);if(t<impact){glow(0,yy,21);g.strokeStyle=color+'88';g.lineWidth=4;g.beginPath();g.moveTo(-6,yy-30);g.lineTo(0,yy);g.stroke();g.fillStyle=color;g.strokeStyle='#533e39';g.lineWidth=2;if(id==='veyra'){g.fillRect(-3,yy,6,25);g.strokeRect(-3,yy,6,25);g.beginPath();g.roundRect(-17,yy-11,34,17,3);g.fill();g.stroke();}else{g.beginPath();g.arc(0,yy,id==='borin'?10:13,0,7);g.fill();g.stroke();spark(-3,yy-4,5);}}else{const k=Math.min(1,(t-impact)*3);glow(0,-8,45*(1-k));ellipse(r*k,color,5*(1-k)+1);for(let i=0;i<7;i++){const a=i*.9,dx=Math.cos(a)*r*k,dy=Math.sin(a)*r*k*.3;g.fillStyle=color;g.beginPath();g.ellipse(dx,dy-18*Math.sin(k*Math.PI),3*(1-k)+1,2,0,0,7);g.fill();}}}
  else if(id==='borin'){const gr=g.createLinearGradient(0,-9,0,4);gr.addColorStop(0,'#f5d196');gr.addColorStop(.5,'#b1864e');gr.addColorStop(1,'#624631');g.fillStyle=gr;g.strokeStyle='#4c3927';g.lineWidth=1.5;g.beginPath();g.ellipse(0,0,12,6,0,0,7);g.fill();g.stroke();g.fillStyle='#786047';g.beginPath();g.ellipse(0,-3,8,3,0,0,7);g.fill();g.stroke();g.fillStyle='#edb16d';g.beginPath();g.arc(0,-5,2.5,0,7);g.fill();for(const xx of [-7,7])spark(xx,0,1.4);}
  else if(id==='thalen'&&slot){for(let i=0;i<6;i++){const a=i*1.05,xx=Math.cos(a)*r*.7,yy=Math.sin(a)*r*.25;g.strokeStyle='#576b40';g.lineWidth=4;g.beginPath();g.moveTo(xx,yy);g.bezierCurveTo(xx+12,yy-14*p,xx-12,yy-30*p,xx*.6,yy-13*p);g.stroke();g.fillStyle='#a5c878';g.beginPath();g.ellipse(xx+3,yy-14*p,7,3,-.5,0,7);g.fill();}}
  else if(id==='oria'){for(let i=0;i<5;i++){const a=t*3+i*1.25;glow(Math.cos(a)*30,-20+Math.sin(a)*8,9);spark(Math.cos(a)*30,-20+Math.sin(a)*8,3);}}
  else if(id==='brakka'&&slot){const tx=(z.tx??x+r)-x,ty=(z.ty??y)-y,ang=Math.atan2(ty,tx);g.strokeStyle='#9b927f';g.lineWidth=2;for(let i=0;i<12;i++){g.beginPath();g.ellipse(tx*i/12,ty*i/12,4,2,ang,0,7);g.stroke();}g.strokeStyle='#ede0b7';g.lineWidth=3;g.beginPath();g.arc(tx,ty,8,ang,ang+4.5);g.stroke();spark(tx,ty,3);}
  else if(id==='haldren'){const k=Math.min(1,t*2.5);ellipse(r*k,color,3*(1-k)+1);for(let i=0;i<6;i++){const a=i*1.05,xx=Math.cos(a)*r*.55,yy=Math.sin(a)*r*.23;g.fillStyle='#ac9270';g.strokeStyle='#594d3f';g.lineWidth=1;g.beginPath();g.moveTo(xx-7,yy);g.lineTo(xx-4,yy-15*Math.sin(k*Math.PI));g.lineTo(xx+5,yy-11*Math.sin(k*Math.PI));g.lineTo(xx+8,yy);g.fill();g.stroke();}}
  else{g.translate(0,-16);slash(r*.8,Math.sin(t*4)*.17);if(id==='brakka')slash(r*.65,Math.PI+t*4);for(let i=0;i<4;i++)spark(Math.cos(i*1.6+t*3)*r*.5,Math.sin(i*1.6+t*3)*r*.17,2);}
  g.restore();return true;
 }
 const oldIcon=SkillArt.icon,badges=new Map();SkillArt.icon=function(id,slot){const sheet=PaintedWorld.sheets.fx59,i=ids.indexOf(id),key=id+slot;if(!sheet?.loaded||i<0)return oldIcon(id,slot);if(badges.has(key))return badges.get(key);const f=sheet.frames[(i<5?slot:2+slot)*5+i%5],c=document.createElement('canvas');c.width=c.height=96;const g=c.getContext('2d');g.fillStyle='#283945';g.fillRect(0,0,96,96);const z=Math.min(84/f.w,84/f.h);g.save();g.translate(48-f.w*z/2,48-f.h*z/2);g.scale(z,z);if(f.clipRects){g.beginPath();for(const b of f.clipRects)g.rect(...b);g.clip();}g.drawImage(sheet.img,f.x,f.y,f.w,f.h,0,0,f.w,f.h);g.restore();const u=c.toDataURL();badges.set(key,u);return u;};
 window.SkillFx59={draw};
})();
