/* service-worker.js – chơi offline. Đổi CACHE_NAME mỗi lần cập nhật. */
const CACHE_NAME = 'canh-cong-painted54';
const ASSETS = [
  'journey.css',
  'js/journey.js',
  'js/painted-motion.js',
  'js/hero-progress.js',
  'js/journey-art.js',
  'js/journey-ui.js',
  'assets/sprites/nara-painted54.webp',
  'assets/sprites/quiet-ground-painted54.webp',

  'assets/sprites/soldier-walk-painted53.webp',
  'assets/sprites/soldierShield-walk-painted53.webp',
  'assets/sprites/goblin-walk-painted53.webp',
  'assets/sprites/orc-walk-painted53.webp',
  'assets/sprites/bandit-walk-painted53.webp',
  'assets/sprites/blackOrc-walk-painted53.webp',
  'assets/sprites/darkKnight-walk-painted53.webp',
  'assets/sprites/darkLord-walk-painted53.webp',
  'assets/sprites/deathKnight-walk-painted53.webp',
  'assets/sprites/skeleton-walk-painted53.webp',
  'assets/sprites/mummy-walk-painted53.webp',
  'assets/sprites/warg-walk-painted53.webp',
  'assets/sprites/frostWolf-walk-painted53.webp',
  'assets/sprites/wolfRider-walk-painted53.webp',
  'assets/sprites/iceGolem-walk-painted53.webp',
  'assets/sprites/magmaGolem-walk-painted53.webp',
  'assets/sprites/magmaLord-walk-painted53.webp',
  'assets/sprites/treant-walk-painted53.webp',
  'assets/sprites/treantKing-walk-painted53.webp',
  'assets/sprites/troll-walk-painted53.webp',
  'assets/sprites/trollKing-walk-painted53.webp',
  'assets/sprites/orcArcher-walk-painted53.webp',
  'assets/sprites/drake-walk-painted53.webp',
  'assets/sprites/imp-walk-painted53.webp',
  'assets/sprites/scorpion-walk-painted53.webp',
  'assets/sprites/shade-walk-painted53.webp',
  'assets/sprites/wraith-walk-painted53.webp',
  'assets/sprites/voidling-walk-painted53.webp',
  'assets/sprites/voidWalker-walk-painted53.webp',
  'assets/sprites/voidLord-walk-painted53.webp',
  'assets/sprites/terrain-forest-painted53.webp',
  'assets/sprites/terrain-castle-painted53.webp',
  'assets/sprites/terrain-desert-painted53.webp',
  'assets/sprites/terrain-ice-painted53.webp',
  'assets/sprites/terrain-lava-painted53.webp',
  'assets/sprites/terrain-chaos-painted53.webp',
  "js/art-world.js",
  "assets/sprites/env-forest-painted52.webp",
  "assets/sprites/env-castle-painted52.webp",
  "assets/sprites/env-desert-painted52.webp",
  "assets/sprites/env-ice-painted52.webp",
  "assets/sprites/env-lava-painted52.webp",
  "assets/sprites/env-chaos-painted52.webp",
  "assets/sprites/equipment-painted52.webp",
  "assets/sprites/towers-painted52.webp",
'./js/battle3d.js', './', './index.html', './style.css', './manifest.json',
  './js/config.js', './js/maps-img.js', './js/campaign.js', './js/save.js', './js/items.js', './js/audio.js', './js/icons.js', './js/art-kit.js', './js/art-chars.js', './js/art-stylized.js',
  './assets/sprites/aldric-painted51.webp', './assets/sprites/bandit-painted51.webp', './assets/sprites/blackOrc-painted51.webp', './assets/sprites/borin-painted51.webp', './assets/sprites/darkKnight-painted51.webp', './assets/sprites/darkLord-painted51.webp', './assets/sprites/deathKnight-painted51.webp', './assets/sprites/drake-painted51.webp', './assets/sprites/dwarf-painted51.webp', './assets/sprites/elf-painted51.webp', './assets/sprites/frostWolf-painted52.webp', './assets/sprites/goblin-painted51.webp', './assets/sprites/iceGolem-painted51.webp', './assets/sprites/imp-painted51.webp', './assets/sprites/lyra-painted51.webp', './assets/sprites/mage-painted51.webp', './assets/sprites/magmaGolem-painted51.webp', './assets/sprites/magmaLord-painted51.webp', './assets/sprites/mummy-painted51.webp', './assets/sprites/orc-painted51.webp', './assets/sprites/orcArcher-painted51.webp', './assets/sprites/pharaoh-walk-painted51.webp', './assets/sprites/scorpion-painted51.webp', './assets/sprites/selene-painted51.webp', './assets/sprites/shade-painted51.webp', './assets/sprites/skeleton-painted51.webp', './assets/sprites/soldier-painted51.webp', './assets/sprites/soldierShield-painted51.webp', './assets/sprites/treant-painted51.webp', './assets/sprites/treantKing-painted51.webp', './assets/sprites/troll-painted51.webp', './assets/sprites/trollKing-painted51.webp', './assets/sprites/voidling-painted51.webp', './assets/sprites/voidLord-painted51.webp', './assets/sprites/voidWalker-painted51.webp', './assets/sprites/warg-painted52.webp', './assets/sprites/wolfRider-painted52.webp', './assets/sprites/wraith-painted51.webp',
  './assets/sprites/pharaoh-painted50.png', './js/art-towers.js', './js/art.js',
  './js/effects.js', './js/level.js', './js/mapart.js', './design/props3d.js', './js/map3d.js', './js/fx3d.js', './js/terrain3d.js', './js/water.js', './js/icons3d.js', './js/lights.js', './js/camera.js', './js/combat.js', './js/enemies.js', './js/units.js', './js/towers.js', './js/spells.js', './js/waves.js',
  './js/game.js', './js/ui.js', './js/main.js',
  './assets/fonts/AlegreyaSC-Black.woff2', './assets/fonts/AlegreyaSans-Bold.woff2', './assets/fonts/AlegreyaSans-ExtraBold.woff2',
  './js/art-img.js', './js/chibi.js', './design/vendor/three.min.js', './design/vendor/BufferGeometryUtils.js', './design/chars3d.js', './design/towers3d.js', './js/art3d.js', './assets/icons/icon-192.png', './assets/icons/icon-512.png', './assets/icons/icon-maskable-512.png'];
self.addEventListener('install', e => e.waitUntil(caches.open(CACHE_NAME).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting())));
self.addEventListener('activate', e => e.waitUntil(caches.keys().then(k => Promise.all(k.filter(x => x !== CACHE_NAME).map(x => caches.delete(x)))).then(() => self.clients.claim())));
self.addEventListener('fetch', e => {
  const r = e.request; if (r.method !== 'GET' || !r.url.startsWith(self.location.origin)) return;
  e.respondWith(fetch(r).then(res => { if (res && res.ok) { const cp=res.clone(); caches.open(CACHE_NAME).then(c=>c.put(r,cp)); } return res; }).catch(() => caches.match(r, {ignoreSearch:true}).then(hit => hit || (r.mode === 'navigate' ? caches.match('./index.html') : undefined))));
});
